
services:
  dify-external-knowledge-base-proxy:
    container_name: dify-ekbp
    image: dify-ekbp
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - RAGFLOW_HOST=${RAGFLOW_HOST}
      - RAGFLOW_PORT=${RAGFLOW_PORT}
      - PROXY_TARGET=${PROXY_TARGET}
    ports:
      - "${SERVER_PORT}:3000"
    env_file:
      - .env

