
services:
  dify-external-knowledge-base-proxy:
    container_name: dify-ekbp
    image: dify-ekbp
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:3000"
    env_file:
      - .env

